### ISSUE TITLE
有时候某些页面突然变大

### ISSUE THREAD

**Issue by ghost** [Firedamp/Rudeness#10]
有时候某些页面突然变大  但重启APP 后又正常  怎么解决

**Comment by Firedamp** [comment]
麻烦整理一个能复现的demo我看一下

**Comment by JoinLi** [comment]
小米note pro 页面适配失败，页面会变大，可以把demo放进去测试一下，请作者尽快解决...

**Comment by Firedamp** [comment]
@JoinLi 请问具体是什么型号，MIUI版本以及Android版本。 没有小米note pro这个型号吧

**Comment by JoinLi** [comment]
有的，你可以在腾讯优测上找一下这个机型， 我可能用的是你早前的版本，我现在改用了你的最新仓库，没有问题了。你可以检查一下你之前的版本demo

**Comment by Firedamp** [comment]
@JoinLi 嗯嗯 因为MIUI有改过系统代码，所以之前有专门对小米修复过一次
