### ISSUE TITLE
用ConstraintLayout布局乱了。和预览图不一致

### ISSUE THREAD

**Issue by for7GG** [Firedamp/Rudeness#11]
![qq 20171013084920](https://user-images.githubusercontent.com/10189846/31525571-c4b61682-aff3-11e7-8f52-faa3986f8cac.png)
![screenshot_2017-10-13-08-50-19-675](https://user-images.githubusercontent.com/10189846/31525572-c70bcfb2-aff3-11e7-8e9d-4b31694cc749.jpeg)

**Comment by for7GG** [comment]
猛然回头发现是AS bug，一动界面元素，竟变成了dp

**Comment by Firedamp** [comment]
AS这个好烦，经常 只是想在界面上点选一个控件，但是会拖动导致xml改变
