### ISSUE TITLE
感觉还是不完善，竖屏显示可用；使用横屏显示时， 会以屏幕的高度作为宽度进行计算，导致设置的值相对于竖屏显示变大

### ISSUE THREAD

**Issue by LingZ6530** [Firedamp/Rudeness#12]
if (resources.getConfiguration().orientation == Configuration.ORIENTATION_LANDSCAPE) {
            resources.getDisplayMetrics().xdpi = size.y / designWidth * 72f;
        } else if (resources.getConfiguration().orientation == Configuration.ORIENTATION_PORTRAIT) {
            resources.getDisplayMetrics().xdpi = size.x / designWidth * 72f;
        }

**Comment by Firedamp** [comment]
是这个理，因为根据宽度缩放的，所以横屏时宽度变大了所以看起来整体都变大了；
你这个方案我也试过，可以保证横屏下与竖屏下控件大小一致，一个pt对应的px保持不变，可是这样的话也会导致一些问题，假如设计稿宽度750，那么竖屏时宽度为750pt，这样的前提下横屏时的宽度就是1000+pt了；
所以我很机智的限制了页面只能竖屏，避免了这个问题。。。
谢谢你的建议。
