### ISSUE TITLE
内存问题讨论

### ISSUE THREAD

**Issue by renjinlong** [Firedamp/Rudeness#13]
之前的我的app 内存占用一直在13兆左右   使用了适配方案后内存后内存现在110多    这个问题怎么解决呢？

**Comment by Firedamp** [comment]
能给我一个demo看一下吗

**Comment by renjinlong** [comment]
我这不是demo   我这是两个相同的copy的项目   都是线上项目    我可以把内存截图给你看  www-ren-com (我的微信)

**Comment by Firedamp** [comment]
嗯嗯 抱歉之前确实没有关注过内存占用的问题

**Comment by renjinlong** [comment]
我现在是activity的create    和fragment的 create  都会初始化屏幕适配方案    你可以看一下你线上的项目的内存占用

**Comment by Firedamp** [comment]
还好 挺正常的
