### ISSUE TITLE
关于页面存在webview的失效问题

### ISSUE THREAD

**Issue by zofnk** [Firedamp/Rudeness#14]
项目中我反复修改了 还是会出现问题
然后我用你的demo试了下也是会
场景如下:demo中的适配页面中随便添加一个WebView
 <WebView
        android:layout_width="match_parent"
        android:layout_height="0pt"
        android:layout_weight="1"/>
当APP第一次进入该页面的时候就会出现除了webview之外的控件适配失效,返回再次进入就可以了,请问下这个怎么解决...有点儿急...麻烦大神看一看~

**Comment by Firedamp** [comment]
请问你用的版本是？  之前有朋友提出类似问题已经解决过了

**Comment by zofnk** [comment]
targetSdkVersion 26
buildToolsVersion "26.0.1"
这是用你那个demo来试的
![image](https://user-images.githubusercontent.com/17997544/32480521-3331d954-c3ca-11e7-80ca-0105548eb7b3.png)
![image](https://user-images.githubusercontent.com/17997544/32480535-426e83fe-c3ca-11e7-8879-eb672210e612.png)

**Comment by Firedamp** [comment]
那你方便把你改的demo，以及手机、系统型号提供一下吗

**Comment by zofnk** [comment]
手机型号 魅蓝note5 Android7.0
另外个荣耀Honor 8 Lite Android7.0 也会出现
demo的话虽然是就改了个布局 我和视屏一起发到你邮箱吧

**Comment by Firedamp** [comment]
383868303@qq.com

**Comment by zofnk** [comment]
我发到 firedamp@vip.qq.com了
Orz
麻烦你看一下 我项目都是用你的适配方案,目前觉得都是还不错的...要改回dp我估计要累瘫...
所以出了这个bug算是蛮头疼 .. 解决的办法就来回翻就你的简书和git ,都没改好 心态有点崩...
麻烦你了...

**Comment by Firedamp** [comment]
没事 两个地址其实是同一个邮箱。 话说，我是在哪里写了这个vip.qq的邮箱的

**Comment by zofnk** [comment]
Issues #5 这里哈 你说的应该也是这个楼吧 我照着几个Issues和评论试了几次都还是这样 Orz...

**Comment by Firedamp** [comment]
麻烦重新打一个zip包给我吧 —。—

**Comment by zofnk** [comment]
已发 只是把工程的build下的文件删了再打包...

**Comment by Firedamp** [comment]
大概查了一下 `WebView`实例化时会调用到`ensureProviderCreated()`，调用`mProvider = getFactory().createWebView(this, new PrivateAccess())`之后会发生DisplayMetrics被重置，你可以先继承`WebView`并重写`setOverScrollMode(int mode)`方法，在方法中调用super之后调用一遍`RudenessScreenHelper.resetDensity(getContext(), 750)`临时规避一下，也可以先重写`Activity`的 `onCreateView(View parent, String name, Context context, AttributeSet attrs)`方法，在调用super之前调用一遍`RudenessScreenHelper.resetDensity(getContext(), 750)`规避，我之后有空会重新整理一下以handle这个case

**Comment by zofnk** [comment]
好的! 非常感谢~~~(,,• ₃ •,,) 
之后还有疑问请多多指教~
