### ISSUE TITLE
Dialog在屏幕旋转完后适配失效问题

### ISSUE THREAD

**Issue by zofnk** [Firedamp/Rudeness#15]
场景:点击弹出Dialog , 正常适配 
旋转屏幕 再回来竖屏 再点击Dialog 适配失效 
再次点击又可以了...我在dialog的生命周期里调用了那个resetDensity方法 还是不行..这个是要怎么解决呀~

**Comment by Firedamp** [comment]
在onConfigurationChanged里调一遍试试

**Comment by zofnk** [comment]
谢谢...当时以为有加的..确认了一下被我写别的代码的时候注释了...麻烦了~
