### ISSUE TITLE
遇到一个问题华为荣耀8，用本方案无效，用了其他适配也无效，只有在布局中设置dp有效，但是dp放到value-1920*1080中还是无效，求助

### ISSUE THREAD

**Issue by Payphone7** [Firedamp/Rudeness#16]

**Comment by Payphone7** [comment]
改手机分辨率是1920*1080的

**Comment by Firedamp** [comment]
具体型号、系统版本、EMUI版本？

**Comment by Payphone7** [comment]
解决了，华为手机虚拟键的事，需求那边不让隐藏虚拟键，很无语

**Comment by Firedamp** [comment]
-.-

**Comment by Payphone7** [comment]
有没有好的设配这种有虚拟键手机的问题，我目前处理的是，多values，并且处理有虚拟键后的，例如1920x1080的华为手机，虚拟键不隐藏是1794x1080，然后建立两个values，方同样的dimens，但是可能需要处理很多分辨率，而且测试机有限，不知道可行不

**Comment by Firedamp** [comment]
有无虚拟键盘 影响的只是高度，在高度的处理上多用一些相对位置，问题应该不大吧。没有必要写多份values吧

**Comment by Payphone7** [comment]
好吧，虽然不太懂，但还是谢谢了，新手一枚，希望大神后期更新时候多多介绍一下虚拟键处理的事吧
