### ISSUE TITLE
请问字体尺寸设置能用PT吗？

### ISSUE THREAD

**Issue by tmxd09887** [Firedamp/Rudeness#19]
首先非常方便的控件！唯一问题是，字体也得用PT做单位适配，是否会在不同机器变模糊？

手头机器少，没有全试过。请有经验的朋友确认下？

谢谢。

**Comment by diguacook** [comment]
所有的单位都是pt，但是我现在在有的手机上做适配会变形

**Comment by tmxd09887** [comment]
是字体变形吗？主要是担心字体变模糊。

**Comment by diguacook** [comment]
这个说不准，要看你设置的大小，我这字体是变大了

**Comment by Firedamp** [comment]
可以

**Comment by diguacook** [comment]
老哥我发现控件变形暂时出现在7.0以及以上的安卓系统上

**Comment by Firedamp** [comment]
@diguacook 给个demo啊老铁
