### ISSUE TITLE
api26上的问题

### ISSUE THREAD

**Issue by wdeo3601** [Firedamp/Rudeness#2]
我把动态设置单位的方法放在 baseActivity 了，大部分界面在 8.0 上没问题，但是有两三个界面（fragment） 一直是尺寸很大， 项目用的 fragmentation 实现的 单 activity + 多 fragment。

然后都是 recyclerview 里边的 item 的布局尺寸不对，用的 mutitype 适配的。但是有的 mutitype适配的也没问题，不知道问题到底出在哪。

**Comment by Firedamp** [comment]
请问你能整理一个简单的demo我来看一下吗

**Comment by wdeo3601** [comment]
@Firedamp 我尽量试试吧，，时间可能有些长

**Comment by Firedamp** [comment]
谢谢，麻烦了

**Comment by wdeo3601** [comment]
@Firedamp 找到原因了，是我的问题。。

 recyclerview适配器加载布局这样写没事
![image](https://user-images.githubusercontent.com/22436965/28807865-9402cbfc-76aa-11e7-8556-d0491a31e283.png)

我之前有各别的是这样写的
![image](https://user-images.githubusercontent.com/22436965/28807924-0663ad42-76ab-11e7-99a9-397383c389b1.png)

**Comment by Firedamp** [comment]
恩，因为把修改的逻辑改到baseActivity了，ui相关用到的context都要使用改过的Activity的context，使用Application的context会有问题
