### ISSUE TITLE
有个数学问题

### ISSUE THREAD

**Issue by hegaojian** [Firedamp/Rudeness#23]
(sqrt(1334^2+750^2))/72 这个公式返回的值怎么试21.25啊，我运行以后怎么得到的是0.6192638002668877，，，，

**Comment by Firedamp** [comment]
sqrt(1334^2+750^2)/72 
     = sqrt(1779556 + 562500)/72
     = sqrt(2342056)/72
     = 1530.3777/72
     = 21.255246
