### ISSUE TITLE
8.0以上页面存在WebView第一次打开还是没有适配

### ISSUE THREAD

**Issue by ftevxk** [Firedamp/Rudeness#24]
模拟器API_27的打开带WebView的页面加上解决方案依旧第一次会没适配，模拟器API_22的没问题

**Comment by gilesdang** [comment]
@ftevxk 您这个问题有解决方案了么

**Comment by gilesdang** [comment]
meta10，打开带有webview的页面，第一次进去适配失败

**Comment by Firedamp** [comment]
应该是EMUI改了一些东西吧，原生Android8.1.0是没问题的，之前许久解决过小米的。请问具体型号与EMUI版本，我找个机器看一下 @gilesdang

**Comment by gilesdang** [comment]
@Firedamp 好了，看了之前您的解决方案，现在解决了，感谢
    @Override
    public void setOverScrollMode(int mode) {
        super.setOverScrollMode(mode);
        RudenessScreenHelper.resetDensity(getContext(), 375);
    }

**Comment by ftevxk** [comment]
我当时是在APP打开的时候先开一个透明带webview的Activity再关掉它来临时解决，之后都一直比较稳定没出现问题了，不过昨天又有报说坚果Pro2打开有概率适配没生效，那个页面是Activity内套Fragment第二个套viewpager再套Fragment，在最里层Fragment第二个没适配到，这个我需要再排查一下是不是我调用那个透明Activity的问题，只是在application启动时调用过一次而已。
