### ISSUE TITLE
我设置了marginTop值没效果

### ISSUE THREAD

**Issue by DevXue** [Firedamp/Rudeness#28]
我在你的Demo中直接修改的  把MainActivity布局换成我的布局  然后根据设计图的尺寸来标注，  但是效果不正确了，偏出很多，  如下图
![1521862663 1](https://user-images.githubusercontent.com/9455329/37860007-194d9222-2f58-11e8-9435-b8eeca0b10d4.jpg)

**Comment by Firedamp** [comment]
请问能给一个简单的demo看一下吗

**Comment by DevXue** [comment]
不好意思， 我用其他方法解决了！
