### ISSUE TITLE
旋转屏幕之后的问题

### ISSUE THREAD

**Issue by shouzhong** [Firedamp/Rudeness#30]
旋转屏幕后，如果配置android:configChanges="orientation|screenSize"，重新设置新的设计尺寸没有效果，会沿用之前旧的设计尺寸，在有滑动控件的布局中滑动的时候视图会变得很大（沿用旧的设计尺寸）

**Comment by shouzhong** [comment]
已经解决了这个问题

**Comment by Firedamp** [comment]
谢谢
