### ISSUE TITLE
ImageView显示非常小的问题

### ISSUE THREAD

**Issue by gxh-apologize** [Firedamp/Rudeness#37]
我两个项目都是用的这个适配，挺不错的。目前第一次在大屏(商米T1, 14寸，横屏，安卓6.0,分辨率1920*1080)开发，发现ImageView在上面显示非常非常小，宽高均是wrap_content，在同分辨率手机上运行是正常的。UI设计稿是1920*1080，切图xhdpi，xxhdpi  ，是切的图片不对？
这个问题可能与此库无关，但是希望有知道原因的告诉一下，非常感谢啦。

**Comment by for7GG** [comment]
限制宽高

**Comment by gxh-apologize** [comment]
不能限制宽高，有些列表的图标大小不太一样。而且，我发现比如我要显示的图标28*28，宽高写成wrap_content就非常非常小，宽高写成28，确实大了，但是虚化的非常厉害.....

**Comment by for7GG** [comment]
图片源问题，根据屏幕尺寸，分辨率请求不同图片

**Comment by gxh-apologize** [comment]
网络图片我基本都限制了宽高了，没什么问题，主要是我本地的图标出现了这个问题。
所以在想是不是图片放错了位置？还是大屏的切图跟手机是不一样的？
不管是加载xhdpi还是xxhdpi 还是xxxhdpi的图标，感觉都是一样的效果 
第一次大屏开发，迷之懵....
