### ISSUE TITLE
虚拟按键高度是配误差较大NavigationBar

### ISSUE THREAD

**Issue by MartinDong** [Firedamp/Rudeness#4]
带有虚拟按键（NavigationBar）的手机高度适配还是有很大的误差的

**Comment by Firedamp** [comment]
感谢支持。因为在适配中只使用宽度来计算适配的长度，所以实际效果看起来是将设计图等比缩放至屏幕宽度大小，这样保证了页面长宽比相等，不过没有考虑到高度，所以需要考虑到页面长度可能会超过整个屏幕的情况。 没有考虑高度有两方面原因：1. 本方案若要考虑高度开销太大也会失去灵活性；2. 同时考虑宽高会造成视图长宽比失调，同样造成适配问题。
