### ISSUE TITLE
有webview的activity出现的问题

### ISSUE THREAD

**Issue by wdeo3601** [Firedamp/Rudeness#5]
第一次进入有 webview 的页面后，返回再进入其他页面，适配就失效了，再次进入webview的页面一次，后边再进其他页面，适配就又好了

**Comment by wdeo3601** [comment]
@Firedamp 暂时通过在 WebActivity 的 setContentView 方法后又调用一边基类的 resetDensity 方法解决了，这解决方法不美丽啊

**Comment by Firedamp** [comment]
我晚点看一下

**Comment by Firedamp** [comment]
已修改代码

**Comment by wdeo3601** [comment]
@Firedamp 问题依旧

**Comment by Firedamp** [comment]
哈？ 兄弟 ， 之前也有朋友与你一样的问题表示已经没问题了， 你能联系我具体探讨一下吗？ firedamp@vip.qq.com

**Comment by wdeo3601** [comment]
@Firedamp 今天跳转到相机拍照，相机横屏后再返回到app又错乱了，上来看到你又更新了 照着你的  在 onstarted 里边又加了一遍，没什么问题了

**Comment by Firedamp** [comment]
嗯嗯 有问题随时联系
